activate: "sigmoid"
batch_size: 8
beta: 0.2
d_ff: 2048
d_layers: 6
d_model: 512
dropout: 0.05
e_layers: 6
focal_loss: false
gamma: 1.5
learning_rate: 0.0001
n_heads: 8
num_epochs: 100
p: 1
reduction: 4
rope: true
tag: "fusion_diff_mse_rope_head8"
wandb_project: "fusion_diff"
weight_decay: 0.001